"""Static, crawlable outputs for the style browser.

Called by build-pages-mvp.py. Writes one HTML page per style under
site/styles/<slug>/, plus sitemap.xml, llms.txt and a plain-link style index
injected into site/index.html. Everything here is derived from the same style
list as site/styles-data.js, so it stays in sync on every build.
"""

from __future__ import annotations

import html
import json
import re
import shutil
from pathlib import Path
from typing import Any

BASE_URL = "https://prompts.vigocreativeai.com"
REPO_URL = "https://github.com/VigoZhao/AI-Visual-Prompt-Cookbook"
AUTHOR = "Vigo Zhao"
AUTHOR_URL = "https://x.com/VigoCreativeAI"
MODELS = "Nano Banana Pro, GPT Image, Midjourney"

# Cloudflare Web Analytics beacon for prompts.vigocreativeai.com (the token is public by design).
ANALYTICS = (
    "<!-- Cloudflare Web Analytics --><script type='module' src='https://static.cloudflareinsights.com/beacon.min.js' "
    "data-cf-beacon='{\"token\": \"8aeae43b7eea4bf991a493b61ca89f1a\"}'></script><!-- End Cloudflare Web Analytics -->"
)

INDEX_START = "<!-- STYLE-INDEX:START (generated by scripts/build-pages-mvp.py) -->"
INDEX_END = "<!-- STYLE-INDEX:END -->"

esc = html.escape
ANCHOR_TAG = re.compile(r"^\[[A-Z]+\]\s*")


def clip(text: str, limit: int = 155) -> str:
    text = re.sub(r"\s+", " ", text).strip()
    if len(text) <= limit:
        return text
    return text[: limit - 1].rsplit(" ", 1)[0].rstrip(",;:—-") + "…"


def page_url(slug: str) -> str:
    return f"{BASE_URL}/site/styles/{slug}/"


def label_for(key: str) -> str:
    return key.replace("_", " ").lower()


def json_ld(style: dict[str, Any]) -> str:
    url = page_url(style["slug"])
    data = [
        {
            "@context": "https://schema.org",
            "@type": "CreativeWork",
            "name": f"{style['name']} — AI image style prompt",
            "description": style["description"],
            "url": url,
            "image": [
                f"{BASE_URL}/styles/{style['slug']}/preview-16x9.jpg",
                f"{BASE_URL}/styles/{style['slug']}/preview-9x16.jpg",
            ],
            "genre": style["category"],
            "keywords": f"{style['name']}, {style['category']}, AI image prompt, style.json, {MODELS}",
            "encodingFormat": "application/json",
            "author": {"@type": "Person", "name": AUTHOR, "url": AUTHOR_URL},
            "isPartOf": {"@type": "Collection", "name": "AI Visual Prompt Cookbook", "url": f"{BASE_URL}/site/"},
            "license": f"{REPO_URL}/blob/main/LICENSE",
        },
        {
            "@context": "https://schema.org",
            "@type": "BreadcrumbList",
            "itemListElement": [
                {"@type": "ListItem", "position": 1, "name": "AI Visual Prompt Cookbook", "item": f"{BASE_URL}/site/"},
                {"@type": "ListItem", "position": 2, "name": style["category"], "item": f"{BASE_URL}/site/?category={style['category'].replace(' ', '+')}"},
                {"@type": "ListItem", "position": 3, "name": style["name"], "item": url},
            ],
        },
    ]
    # "</" inside a script block would end it early.
    return json.dumps(data, ensure_ascii=False, indent=2).replace("</", "<\\/")


def related_for(style: dict[str, Any], styles: list[dict[str, Any]], limit: int = 6) -> list[dict[str, Any]]:
    """Other sets of the same family first, then the precomputed similar styles."""
    by_slug = {s["slug"]: s for s in styles}
    family = [s for s in styles if style.get("family") and s.get("family") == style["family"] and s["slug"] != style["slug"]]
    similar = [by_slug[slug] for slug in style.get("similar", []) if slug in by_slug]
    return (family + similar)[:limit]


def case_label(name: str) -> str:
    if re.fullmatch(r"[a-z0-9]+(-[a-z0-9]+)+", name):
        return " ".join(part.capitalize() for part in name.split("-"))
    return name


def samples_block(style: dict[str, Any]) -> str:
    samples = style.get("samples") or []
    if len(samples) < 2:
        return ""
    examples = json.loads(style["jsonText"]).get("examples") or []
    figures = []
    for sample in samples:
        item = examples[sample["index"]] if sample["index"] < len(examples) else {}
        label = case_label(str(item.get("case_name") or f"Example {sample['index'] + 1}"))
        src = "../../" + sample["img16"]  # data paths are relative to site/
        figures.append(
            f"""          <figure>
            <img src="{esc(src)}" alt="{esc(style['name'])} — example: {esc(label)}" loading="lazy" width="800" height="450">
            <figcaption>{esc(label)}</figcaption>
          </figure>"""
        )
    return f"""
      <section class="sp-cases" aria-label="Example cases">
        <h2>{len(samples)} example cases</h2>
        <p>Same style.json, different subjects. Each case's values are in the <code>examples</code> section of the JSON.</p>
        <div class="sp-case-grid">
{chr(10).join(figures)}
        </div>
      </section>
"""


def style_page(style: dict[str, Any], styles: list[dict[str, Any]]) -> str:
    slug = style["slug"]
    name = style["name"]
    title = f"{name} — AI Image Style Prompt for Nano Banana Pro & GPT Image"
    description = clip(f"{style['description']} Free style.json for {MODELS}.")
    url = page_url(slug)
    og_image = f"{BASE_URL}/styles/{slug}/preview-16x9.jpg"
    category_q = style["category"].replace(" ", "+")

    anchors = "\n".join(f"          <li>{esc(ANCHOR_TAG.sub('', a))}</li>" for a in style["anchors"])
    variables = "".join(f"<li><code>{esc(v)}</code> <span>{esc(label_for(v))}</span></li>" for v in style["variables"])
    related = "\n".join(
        f"""        <a class="related-card" href="../{esc(r['slug'])}/">
          <img src="../../../assets/thumbs/{esc(r['slug'])}-16x9.jpg" alt="{esc(r['name'])} style preview" loading="lazy" width="640" height="360">
          <span>{esc(r['name'])}</span>
        </a>"""
        for r in related_for(style, styles)
    )

    return f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{esc(title)}</title>
    <meta name="description" content="{esc(description)}">
    <link rel="canonical" href="{url}">
    <meta property="og:type" content="article">
    <meta property="og:site_name" content="AI Visual Prompt Cookbook">
    <meta property="og:title" content="{esc(title)}">
    <meta property="og:description" content="{esc(description)}">
    <meta property="og:url" content="{url}">
    <meta property="og:image" content="{og_image}">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="{esc(title)}">
    <meta name="twitter:description" content="{esc(description)}">
    <meta name="twitter:image" content="{og_image}">
    <meta name="twitter:site" content="@VigoCreativeAI">
    <link rel="icon" href="../../favicon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="../../favicon-180.png">
    <script>
      try {{
        document.documentElement.dataset.theme = localStorage.getItem("cookbook-theme") || "dark";
      }} catch {{
        document.documentElement.dataset.theme = "dark";
      }}
    </script>
    <link rel="stylesheet" href="../../style-page.css?v=2">
    <script type="application/ld+json">
{json_ld(style)}
    </script>
  </head>
  <body>
    <main class="sp-shell">
      <nav class="sp-crumbs" aria-label="Breadcrumb">
        <a href="../../">AI Visual Prompt Cookbook</a>
        <span aria-hidden="true">/</span>
        <a href="../../?category={esc(category_q)}">{esc(style['category'])}</a>
        <span aria-hidden="true">/</span>
        <span aria-current="page">{esc(name)}</span>
      </nav>

      <header class="sp-hero">
        <p class="sp-eyebrow">{esc(style['category'])} · AI image style prompt</p>
        <h1>{esc(name)}</h1>
        <p class="sp-lede">{esc(style['description'])}</p>
        <div class="sp-actions">
          <button class="sp-button primary" type="button" data-copy-json>Copy style.json</button>
          <a class="sp-button" href="{REPO_URL}" title="Star the repo to get new style drops">★ Star on GitHub</a>
          <a class="sp-button" href="../../#{esc(slug)}">Open in gallery</a>
          <a class="sp-button" href="{REPO_URL}/tree/main/styles/{esc(slug)}">View on GitHub</a>
        </div>
      </header>

      <section class="sp-previews" aria-label="Example images">
        <figure class="wide">
          <img src="../../../styles/{esc(slug)}/preview-16x9.jpg" alt="{esc(name)} — example AI image, 16:9">
          <figcaption>16:9 example</figcaption>
        </figure>
        <figure class="tall">
          <img src="../../../styles/{esc(slug)}/preview-9x16.jpg" alt="{esc(name)} — example AI image, 9:16" loading="lazy">
          <figcaption>9:16 example</figcaption>
        </figure>
      </section>

{samples_block(style)}
      <div class="sp-columns">
        <section>
          <h2>What this style does</h2>
          <p>{esc(style['summary'])}</p>
          <h2>Signature traits</h2>
          <ul class="sp-anchors">
{anchors}
          </ul>
        </section>
        <aside>
          <h2>How to use</h2>
          <ol class="sp-steps">
            <li>Copy the <code>style.json</code> below.</li>
            <li>Paste it into ChatGPT, Gemini or Claude, or any LLM image workflow ({esc(MODELS)}).</li>
            <li>Swap the variables for your own subject and generate.</li>
          </ol>
          <h2>Variables</h2>
          <ul class="sp-vars">{variables}</ul>
        </aside>
      </div>

      <section class="sp-json">
        <div class="sp-json-head">
          <h2>style.json</h2>
          <button class="sp-button primary" type="button" data-copy-json>Copy</button>
        </div>
        <pre id="styleJson">{esc(style['jsonText'].rstrip())}</pre>
      </section>

      <section class="sp-related">
        <h2>Similar styles</h2>
        <div class="related-grid">
{related}
        </div>
        <p><a href="../../">Browse all {len(styles)} styles →</a></p>
      </section>

      <footer class="sp-footer">
        Curated by <a href="{AUTHOR_URL}">{AUTHOR} (@VigoCreativeAI)</a> ·
        <a href="{REPO_URL}">AI Visual Prompt Cookbook on GitHub</a>
      </footer>
    </main>
    <div class="sp-toast" id="toast" role="status" aria-live="polite"></div>
    <script>
      document.querySelectorAll("[data-copy-json]").forEach((button) => {{
        button.addEventListener("click", async () => {{
          const text = document.getElementById("styleJson").textContent;
          let ok = false;
          try {{ await navigator.clipboard.writeText(text); ok = true; }} catch {{}}
          const toast = document.getElementById("toast");
          toast.textContent = ok ? "Copied style.json" : "Copy failed. Select the JSON and copy it manually.";
          toast.classList.add("show");
          setTimeout(() => toast.classList.remove("show"), 1800);
        }});
      }});
    </script>
    {ANALYTICS}
  </body>
</html>
"""


def write_style_pages(site_dir: Path, styles: list[dict[str, Any]]) -> None:
    pages_dir = site_dir / "styles"
    pages_dir.mkdir(exist_ok=True)
    keep = {s["slug"] for s in styles}
    for child in pages_dir.iterdir():
        if child.is_dir() and child.name not in keep:
            shutil.rmtree(child)
    for style in styles:
        out = pages_dir / style["slug"] / "index.html"
        out.parent.mkdir(exist_ok=True)
        out.write_text(style_page(style, styles), encoding="utf-8")


def write_sitemap(root: Path, styles: list[dict[str, Any]]) -> None:
    urls = [f"{BASE_URL}/site/"] + [page_url(s["slug"]) for s in styles]
    body = "\n".join(f"  <url><loc>{esc(u)}</loc></url>" for u in urls)
    (root / "sitemap.xml").write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        f"{body}\n</urlset>\n",
        encoding="utf-8",
    )


def write_llms_txt(root: Path, styles: list[dict[str, Any]], categories: list[str]) -> None:
    lines = [
        "# AI Visual Prompt Cookbook",
        "",
        f"> {len(styles)} plug-and-play visual style packs for AI image generation ({MODELS}, ChatGPT, Gemini, Claude).",
        "> Each style is one structured style.json: paste it into an LLM image workflow, replace the variables, keep the look.",
        "",
        f"Curated by {AUTHOR} ({AUTHOR_URL}). Source: {REPO_URL}",
        "",
        "## How to use a style",
        "",
        "1. Pick a style below and open its page, or fetch its raw style.json.",
        "2. Paste the whole JSON into the chat or image workflow.",
        "3. Replace the values in `environment_variables` (subject, headline text...) and generate.",
        "",
        f"- [Online gallery]({BASE_URL}/site/): searchable previews of every style",
        f"- [Catalog]({REPO_URL}/blob/main/docs/CATALOG.md): full list with categories",
        "",
    ]
    for category in categories:
        lines += [f"## {category}", ""]
        for s in styles:
            if s["category"] == category:
                lines.append(
                    f"- [{s['name']}]({page_url(s['slug'])}): {clip(s['description'], 220)} "
                    f"Raw JSON: {BASE_URL}/styles/{s['slug']}/style.json"
                )
        lines.append("")
    (root / "llms.txt").write_text("\n".join(lines), encoding="utf-8")


def inject_index(index_html: Path, styles: list[dict[str, Any]], categories: list[str]) -> None:
    text = index_html.read_text(encoding="utf-8")
    if INDEX_START not in text or INDEX_END not in text:
        raise ValueError(f"{index_html} is missing the STYLE-INDEX markers")
    groups = []
    for category in categories:
        links = "\n".join(
            f'            <li><a href="styles/{esc(s["slug"])}/">{esc(s["name"])}</a></li>'
            for s in styles
            if s["category"] == category
        )
        groups.append(
            f"""        <div class="index-group">
          <h3>{esc(category)}</h3>
          <ul>
{links}
          </ul>
        </div>"""
        )
    block = f"{INDEX_START}\n" + "\n".join(groups) + f"\n        {INDEX_END}"
    pattern = re.escape(INDEX_START) + r".*?" + re.escape(INDEX_END)
    index_html.write_text(re.sub(pattern, lambda _: block, text, flags=re.DOTALL), encoding="utf-8")


def build_all(root: Path, site_dir: Path, styles: list[dict[str, Any]], categories: list[str]) -> None:
    write_style_pages(site_dir, styles)
    write_sitemap(root, styles)
    write_llms_txt(root, styles, categories)
    inject_index(site_dir / "index.html", styles, categories)
